-- MON-003: generated by drizzle-kit, grouped by table to avoid repeated rewrites.
-- Existing minor units, defaults and nullability are preserved; no rescaling.
-- Run via the transactional migration runner after a verified backup/rehearsal.
SET LOCAL lock_timeout = '5s';--> statement-breakpoint
SET LOCAL statement_timeout = '15min';--> statement-breakpoint
ALTER TABLE "organization"
  ALTER COLUMN "bill_approval_threshold" TYPE bigint USING "bill_approval_threshold"::bigint,
  ALTER COLUMN "mileage_rate" TYPE bigint USING "mileage_rate"::bigint;
--> statement-breakpoint
ALTER TABLE "journal_line"
  ALTER COLUMN "debit_amount" TYPE bigint USING "debit_amount"::bigint,
  ALTER COLUMN "credit_amount" TYPE bigint USING "credit_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "tax_return_line"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "contact"
  ALTER COLUMN "credit_limit" TYPE bigint USING "credit_limit"::bigint;
--> statement-breakpoint
ALTER TABLE "credit_note"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint,
  ALTER COLUMN "amount_applied" TYPE bigint USING "amount_applied"::bigint,
  ALTER COLUMN "amount_remaining" TYPE bigint USING "amount_remaining"::bigint;
--> statement-breakpoint
ALTER TABLE "credit_note_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "customer_credit"
  ALTER COLUMN "original_amount" TYPE bigint USING "original_amount"::bigint,
  ALTER COLUMN "amount_remaining" TYPE bigint USING "amount_remaining"::bigint;
--> statement-breakpoint
ALTER TABLE "invoice"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint,
  ALTER COLUMN "amount_paid" TYPE bigint USING "amount_paid"::bigint,
  ALTER COLUMN "amount_due" TYPE bigint USING "amount_due"::bigint;
--> statement-breakpoint
ALTER TABLE "invoice_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "quote"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint,
  ALTER COLUMN "billed_total" TYPE bigint USING "billed_total"::bigint;
--> statement-breakpoint
ALTER TABLE "quote_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "sales_receipt"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint;
--> statement-breakpoint
ALTER TABLE "sales_receipt_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "bill"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint,
  ALTER COLUMN "amount_paid" TYPE bigint USING "amount_paid"::bigint,
  ALTER COLUMN "amount_due" TYPE bigint USING "amount_due"::bigint;
--> statement-breakpoint
ALTER TABLE "bill_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "debit_note"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint,
  ALTER COLUMN "amount_applied" TYPE bigint USING "amount_applied"::bigint,
  ALTER COLUMN "amount_remaining" TYPE bigint USING "amount_remaining"::bigint;
--> statement-breakpoint
ALTER TABLE "debit_note_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "goods_receipt_line"
  ALTER COLUMN "unit_cost" TYPE bigint USING "unit_cost"::bigint;
--> statement-breakpoint
ALTER TABLE "landed_cost_allocation"
  ALTER COLUMN "total_cost_amount" TYPE bigint USING "total_cost_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "landed_cost_component"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "landed_cost_line_allocation"
  ALTER COLUMN "allocated_amount" TYPE bigint USING "allocated_amount"::bigint,
  ALTER COLUMN "allocation_basis" TYPE bigint USING "allocation_basis"::bigint;
--> statement-breakpoint
ALTER TABLE "purchase_order"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint;
--> statement-breakpoint
ALTER TABLE "purchase_order_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "purchase_requisition"
  ALTER COLUMN "subtotal" TYPE bigint USING "subtotal"::bigint,
  ALTER COLUMN "tax_total" TYPE bigint USING "tax_total"::bigint,
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint;
--> statement-breakpoint
ALTER TABLE "purchase_requisition_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "bank_account"
  ALTER COLUMN "balance" TYPE bigint USING "balance"::bigint,
  ALTER COLUMN "low_balance_threshold" TYPE bigint USING "low_balance_threshold"::bigint;
--> statement-breakpoint
ALTER TABLE "bank_reconciliation"
  ALTER COLUMN "start_balance" TYPE bigint USING "start_balance"::bigint,
  ALTER COLUMN "end_balance" TYPE bigint USING "end_balance"::bigint;
--> statement-breakpoint
ALTER TABLE "bank_statement_import"
  ALTER COLUMN "opening_balance" TYPE bigint USING "opening_balance"::bigint,
  ALTER COLUMN "closing_balance" TYPE bigint USING "closing_balance"::bigint;
--> statement-breakpoint
ALTER TABLE "bank_transaction"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint,
  ALTER COLUMN "balance" TYPE bigint USING "balance"::bigint;
--> statement-breakpoint
ALTER TABLE "budget_line"
  ALTER COLUMN "total" TYPE bigint USING "total"::bigint;
--> statement-breakpoint
ALTER TABLE "budget_period"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "expense_claim"
  ALTER COLUMN "total_amount" TYPE bigint USING "total_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "expense_item"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint,
  ALTER COLUMN "mileage_rate" TYPE bigint USING "mileage_rate"::bigint;
--> statement-breakpoint
ALTER TABLE "inventory_cost_layer"
  ALTER COLUMN "unit_cost" TYPE bigint USING "unit_cost"::bigint;
--> statement-breakpoint
ALTER TABLE "inventory_item"
  ALTER COLUMN "purchase_price" TYPE bigint USING "purchase_price"::bigint,
  ALTER COLUMN "sale_price" TYPE bigint USING "sale_price"::bigint,
  ALTER COLUMN "average_cost" TYPE bigint USING "average_cost"::bigint,
  ALTER COLUMN "standard_cost" TYPE bigint USING "standard_cost"::bigint,
  ALTER COLUMN "total_value" TYPE bigint USING "total_value"::bigint;
--> statement-breakpoint
ALTER TABLE "inventory_item_supplier"
  ALTER COLUMN "purchase_price" TYPE bigint USING "purchase_price"::bigint;
--> statement-breakpoint
ALTER TABLE "inventory_layer_consumption"
  ALTER COLUMN "unit_cost" TYPE bigint USING "unit_cost"::bigint;
--> statement-breakpoint
ALTER TABLE "inventory_movement"
  ALTER COLUMN "unit_cost" TYPE bigint USING "unit_cost"::bigint,
  ALTER COLUMN "value" TYPE bigint USING "value"::bigint;
--> statement-breakpoint
ALTER TABLE "inventory_variant"
  ALTER COLUMN "purchase_price" TYPE bigint USING "purchase_price"::bigint,
  ALTER COLUMN "sale_price" TYPE bigint USING "sale_price"::bigint;
--> statement-breakpoint
ALTER TABLE "stock_take_line"
  ALTER COLUMN "value_adjustment" TYPE bigint USING "value_adjustment"::bigint;
--> statement-breakpoint
ALTER TABLE "price_list_item"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint;
--> statement-breakpoint
ALTER TABLE "milestone_assignment"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "project"
  ALTER COLUMN "budget" TYPE bigint USING "budget"::bigint,
  ALTER COLUMN "hourly_rate" TYPE bigint USING "hourly_rate"::bigint,
  ALTER COLUMN "fixed_price" TYPE bigint USING "fixed_price"::bigint,
  ALTER COLUMN "total_billed" TYPE bigint USING "total_billed"::bigint;
--> statement-breakpoint
ALTER TABLE "project_billable_item"
  ALTER COLUMN "cost_amount" TYPE bigint USING "cost_amount"::bigint,
  ALTER COLUMN "billed_amount" TYPE bigint USING "billed_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "project_member"
  ALTER COLUMN "hourly_rate" TYPE bigint USING "hourly_rate"::bigint,
  ALTER COLUMN "cost_rate" TYPE bigint USING "cost_rate"::bigint;
--> statement-breakpoint
ALTER TABLE "project_milestone"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint,
  ALTER COLUMN "invoiced_amount_cents" TYPE bigint USING "invoiced_amount_cents"::bigint;
--> statement-breakpoint
ALTER TABLE "time_entry"
  ALTER COLUMN "hourly_rate" TYPE bigint USING "hourly_rate"::bigint;
--> statement-breakpoint
ALTER TABLE "asset_category"
  ALTER COLUMN "default_residual_value" TYPE bigint USING "default_residual_value"::bigint;
--> statement-breakpoint
ALTER TABLE "asset_revaluation"
  ALTER COLUMN "previous_carrying_amount" TYPE bigint USING "previous_carrying_amount"::bigint,
  ALTER COLUMN "revalued_amount" TYPE bigint USING "revalued_amount"::bigint,
  ALTER COLUMN "change_amount" TYPE bigint USING "change_amount"::bigint,
  ALTER COLUMN "surplus_amount" TYPE bigint USING "surplus_amount"::bigint,
  ALTER COLUMN "impairment_amount" TYPE bigint USING "impairment_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "cwip_cost"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "depreciation_entry"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "fixed_asset"
  ALTER COLUMN "purchase_price" TYPE bigint USING "purchase_price"::bigint,
  ALTER COLUMN "residual_value" TYPE bigint USING "residual_value"::bigint,
  ALTER COLUMN "accumulated_depreciation" TYPE bigint USING "accumulated_depreciation"::bigint,
  ALTER COLUMN "net_book_value" TYPE bigint USING "net_book_value"::bigint,
  ALTER COLUMN "revalued_amount" TYPE bigint USING "revalued_amount"::bigint,
  ALTER COLUMN "revaluation_surplus_balance" TYPE bigint USING "revaluation_surplus_balance"::bigint,
  ALTER COLUMN "disposal_amount" TYPE bigint USING "disposal_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "compensation_band"
  ALTER COLUMN "min_salary" TYPE bigint USING "min_salary"::bigint,
  ALTER COLUMN "mid_salary" TYPE bigint USING "mid_salary"::bigint,
  ALTER COLUMN "max_salary" TYPE bigint USING "max_salary"::bigint;
--> statement-breakpoint
ALTER TABLE "compensation_review"
  ALTER COLUMN "total_budget" TYPE bigint USING "total_budget"::bigint;
--> statement-breakpoint
ALTER TABLE "compensation_review_entry"
  ALTER COLUMN "current_salary" TYPE bigint USING "current_salary"::bigint,
  ALTER COLUMN "proposed_salary" TYPE bigint USING "proposed_salary"::bigint;
--> statement-breakpoint
ALTER TABLE "contractor"
  ALTER COLUMN "hourly_rate" TYPE bigint USING "hourly_rate"::bigint;
--> statement-breakpoint
ALTER TABLE "contractor_payment"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "deduction_type"
  ALTER COLUMN "default_amount" TYPE bigint USING "default_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "employee_deduction"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "employee_tax_config"
  ALTER COLUMN "additional_withholding" TYPE bigint USING "additional_withholding"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_bonus"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_employee"
  ALTER COLUMN "salary" TYPE bigint USING "salary"::bigint,
  ALTER COLUMN "hourly_rate" TYPE bigint USING "hourly_rate"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_item"
  ALTER COLUMN "gross_amount" TYPE bigint USING "gross_amount"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "deductions" TYPE bigint USING "deductions"::bigint,
  ALTER COLUMN "net_amount" TYPE bigint USING "net_amount"::bigint,
  ALTER COLUMN "overtime_amount" TYPE bigint USING "overtime_amount"::bigint,
  ALTER COLUMN "bonus_amount" TYPE bigint USING "bonus_amount"::bigint,
  ALTER COLUMN "pre_tax_deductions" TYPE bigint USING "pre_tax_deductions"::bigint,
  ALTER COLUMN "post_tax_deductions" TYPE bigint USING "post_tax_deductions"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_item_deduction"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_item_employer_tax"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_item_overtime"
  ALTER COLUMN "regular_amount" TYPE bigint USING "regular_amount"::bigint,
  ALTER COLUMN "overtime_amount" TYPE bigint USING "overtime_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_item_tax_breakdown"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_run"
  ALTER COLUMN "total_gross" TYPE bigint USING "total_gross"::bigint,
  ALTER COLUMN "total_deductions" TYPE bigint USING "total_deductions"::bigint,
  ALTER COLUMN "total_net" TYPE bigint USING "total_net"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_settings"
  ALTER COLUMN "ss_wage_base_cents" TYPE bigint USING "ss_wage_base_cents"::bigint,
  ALTER COLUMN "addl_medicare_threshold_cents" TYPE bigint USING "addl_medicare_threshold_cents"::bigint,
  ALTER COLUMN "futa_wage_base_cents" TYPE bigint USING "futa_wage_base_cents"::bigint,
  ALTER COLUMN "suta_wage_base_cents" TYPE bigint USING "suta_wage_base_cents"::bigint;
--> statement-breakpoint
ALTER TABLE "payroll_tax_payment"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payslip"
  ALTER COLUMN "gross_amount" TYPE bigint USING "gross_amount"::bigint,
  ALTER COLUMN "net_amount" TYPE bigint USING "net_amount"::bigint,
  ALTER COLUMN "tax_amount" TYPE bigint USING "tax_amount"::bigint,
  ALTER COLUMN "ytd_gross" TYPE bigint USING "ytd_gross"::bigint,
  ALTER COLUMN "ytd_net" TYPE bigint USING "ytd_net"::bigint,
  ALTER COLUMN "ytd_tax" TYPE bigint USING "ytd_tax"::bigint;
--> statement-breakpoint
ALTER TABLE "tax_allowance_config"
  ALTER COLUMN "allowance_value_cents" TYPE bigint USING "allowance_value_cents"::bigint,
  ALTER COLUMN "standard_deduction_cents" TYPE bigint USING "standard_deduction_cents"::bigint;
--> statement-breakpoint
ALTER TABLE "tax_bracket"
  ALTER COLUMN "min_income" TYPE bigint USING "min_income"::bigint,
  ALTER COLUMN "max_income" TYPE bigint USING "max_income"::bigint,
  ALTER COLUMN "base_amount_cents" TYPE bigint USING "base_amount_cents"::bigint,
  ALTER COLUMN "standard_deduction_cents" TYPE bigint USING "standard_deduction_cents"::bigint;
--> statement-breakpoint
ALTER TABLE "payment"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payment_allocation"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "recurring_template_line"
  ALTER COLUMN "unit_price" TYPE bigint USING "unit_price"::bigint,
  ALTER COLUMN "debit_amount" TYPE bigint USING "debit_amount"::bigint,
  ALTER COLUMN "credit_amount" TYPE bigint USING "credit_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "accrual_entry"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "accrual_schedule"
  ALTER COLUMN "total_amount" TYPE bigint USING "total_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "revenue_entry"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "revenue_schedule"
  ALTER COLUMN "total_amount" TYPE bigint USING "total_amount"::bigint,
  ALTER COLUMN "recognized_amount" TYPE bigint USING "recognized_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "loan"
  ALTER COLUMN "principal_amount" TYPE bigint USING "principal_amount"::bigint,
  ALTER COLUMN "monthly_payment" TYPE bigint USING "monthly_payment"::bigint;
--> statement-breakpoint
ALTER TABLE "loan_schedule"
  ALTER COLUMN "principal_amount" TYPE bigint USING "principal_amount"::bigint,
  ALTER COLUMN "interest_amount" TYPE bigint USING "interest_amount"::bigint,
  ALTER COLUMN "total_payment" TYPE bigint USING "total_payment"::bigint,
  ALTER COLUMN "remaining_balance" TYPE bigint USING "remaining_balance"::bigint;
--> statement-breakpoint
ALTER TABLE "bill_of_materials"
  ALTER COLUMN "labor_cost_cents" TYPE bigint USING "labor_cost_cents"::bigint,
  ALTER COLUMN "overhead_cost_cents" TYPE bigint USING "overhead_cost_cents"::bigint;
--> statement-breakpoint
ALTER TABLE "deal"
  ALTER COLUMN "value_cents" TYPE bigint USING "value_cents"::bigint;
--> statement-breakpoint
ALTER TABLE "payment_batch"
  ALTER COLUMN "total_amount" TYPE bigint USING "total_amount"::bigint;
--> statement-breakpoint
ALTER TABLE "payment_batch_item"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "scheduled_payment"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
--> statement-breakpoint
ALTER TABLE "consolidation_elimination_entry"
  ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint,
  ALTER COLUMN "variance_amount" TYPE bigint USING "variance_amount"::bigint;
