import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { bankAccountIdField } from "@/lib/api/bank-account-wire";
import { statementFields, bulkFields, profileFields } from "@/lib/api/bank-import-wire";
import { previewBankImport, commitBankImport, previewBulkBankImport, commitBulkBankImport, getBankImport, getBankImportProfile, saveBankImportProfile, deleteBankImportProfile } from "@/lib/api/bank-imports";
import { wrapTool } from "@/lib/mcp/errors";
import type { AuthContext } from "@/lib/api/auth-context";

export function registerBankImportTools(server: McpServer, ctx: AuthContext) {
  const bank = { bankAccountId: bankAccountIdField };
  server.registerTool("preview_bank_statement_import", { description: "Read-only preview of an owned bank statement. Text amounts use decimal major units and the bank currency scale; BAI2 uses integer minor units. CSV amountMinor/balanceMinor accept canonical integer strings; aliases must agree. Safe numeric coexistence +/-9007199254740991. Requires manage:banking. Returns {preview} with numeric money plus Minor aliases, first 100 transactions, full rowCount and existing/within-file duplicates.", inputSchema: z.object({ ...bank, ...statementFields }).strict() }, ({ bankAccountId, ...input }) => wrapTool(ctx, () => previewBankImport(ctx, bankAccountId, input)));
  server.registerTool("import_bank_statement", { description: "Atomically import an owned bank statement and history/balance/audit. Same money contract as preview_bank_statement_import; dates must be open. Duplicate hashes serialize under bank/org locks, including within-file and concurrent retries; repeated imports may add history but no duplicate transaction or balance movement. Rules add suggestions only, without posting/reconciliation. Returns {import} with preview money/Minor aliases and imported/duplicateCount/importId.", inputSchema: z.object({ ...bank, ...statementFields }).strict() }, ({ bankAccountId, ...input }) => wrapTool(ctx, () => commitBankImport(ctx, bankAccountId, input)));
  server.registerTool("preview_bank_transaction_import", { description: "Read-only preview of mapped bulk bank rows. amount numeric/text and amountExact text are decimal major units; amountMinor is a canonical integer string, all aliases must agree. Split debit/credit are decimal major units. Resolves literal owned bank names/currency scales; invalid rows report errors without writes. Returns preview data preserving input major-unit amount plus canonical amountExact/amountMinor, validCount/totalCount. Requires manage:banking.", inputSchema: z.object(bulkFields).strict() }, input => wrapTool(ctx, () => previewBulkBankImport(ctx, input)));
  server.registerTool("import_bank_transactions", { description: "Atomically import mapped bank rows, per-account history, bulk job and audit. Money contract matches preview_bank_transaction_import. Invalid rows/locked dates roll back the whole batch before commit. Safe numeric range applies; duplicates serialize and skip on retries. Does not update bank balances or post journals; rules supply suggestions only. Returns {job,duplicates}; counts are rows, not money. Requires manage:banking.", inputSchema: z.object(bulkFields).strict() }, input => wrapTool(ctx, () => commitBulkBankImport(ctx, input)));
  server.registerTool("get_bank_statement_import", { description: "Read one organization-owned import and live bank plus first 100 owned transactions, ordered by date/id. Numeric balances/amounts retain currency minor units with matching Minor strings, safe numeric range only. Returns {import}; no writes.", inputSchema: z.object({ importId: z.string().uuid().describe("Organization-owned bank statement import UUID") }).strict() }, input => wrapTool(ctx, () => getBankImport(ctx, input.importId)));
  server.registerTool("get_bank_import_profile", { description: "Read the effective CSV/TSV parser profile of a live owned bank. Returns {profile} settings or null for auto detection; no money or writes.", inputSchema: z.object(bank).strict() }, input => wrapTool(ctx, () => getBankImportProfile(ctx, input.bankAccountId)));
  server.registerTool("save_bank_import_profile", { description: "Replace the owned bank's CSV/TSV parser profile atomically with audit. Controls separators, date order, delimiter and split debit sign. Dates remain Gregorian date-only; UTC and decoded UTF-8 only. Other formats retain their own syntax. Returns {profile}; requires manage:banking.", inputSchema: z.object({ ...bank, ...profileFields }).strict() }, ({ bankAccountId, ...input }) => wrapTool(ctx, () => saveBankImportProfile(ctx, bankAccountId, input)));
  server.registerTool("delete_bank_import_profile", { description: "Remove all parser profiles for the live owned bank atomically with audit, restoring auto detection. Returns {success:true}; requires manage:banking.", inputSchema: z.object(bank).strict() }, input => wrapTool(ctx, () => deleteBankImportProfile(ctx, input.bankAccountId)));
}
