import { registerPayrollCompensationTools } from "./payroll-compensation";
import { registerPayrollPaymentTools } from "./payroll-payments";
import { registerPayrollRunTools } from "./payroll-runs";
import { registerPayrollTimeTools } from "./payroll-time";
import { registerPayrollConfigTools } from "./payroll-config";
import { registerPayrollMasterTools } from "./payroll-master";
import { registerInventoryValuationTools } from "./inventory-valuation";
import { registerInventoryMasterTools } from "./inventory-master";
import { registerBankDocumentMatchTools } from "./bank-document-matches";
import { registerBankTransferTools } from "./bank-transfers";
import { registerBankCategorizationTools } from "./bank-categorization";
import { registerBankImportTools } from "./bank-imports";
import { registerBankAccountTools } from "./bank-accounts";
import { registerBankTransactionReadTools } from "./bank-transaction-reads";
import { registerGoodsReceiptTools } from "./goods-receipts";
import { registerPaymentBatchTools } from "./payment-batches";
import { registerScheduledPaymentTools } from "./scheduled-payments";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { AuthContext } from "@/lib/api/auth-context";
import { registerOrganizationTools } from "./organization";
import { registerAccountTools } from "./accounts";
import { registerEntryTools } from "./entries";
import { registerContactTools } from "./contacts";
import { registerInvoiceTools } from "./invoices";
import { registerInvoiceLifecycleTools } from "./invoice-lifecycle";
import { registerBillTools } from "./bills";
import { registerReportTools } from "./reports";
import { registerNotificationTools } from "./notifications";
import { registerRoleTools } from "./roles";
import { registerTimeTrackingTools } from "./time-tracking";
import { registerWebhookTools } from "./webhooks";
import { registerReportScheduleTools } from "./report-schedule-tools";
import { registerApprovalTools } from "./approvals";
import { registerBankRuleTools } from "./bank-rules";
import { registerBankReconciliationTools } from "./bank-reconciliations";
import { registerDocumentTools } from "./documents";
import { registerIntegrationTools } from "./integrations";
import { registerEmailTools } from "./email";
import { registerPeriodCloseTools } from "./period-close";
import { registerImportExportTools } from "./import-export";
import { registerTrashTools } from "./trash";
import { registerBackupTools } from "./backups";
import { registerCurrencyTools } from "./currencies";
import { registerTaxRateTools } from "./tax-rates";
import { registerTaxLookupTools } from "./tax-lookup";
import { registerTaxTools } from "./tax";
import { registerConsolidationTools } from "./consolidation";
import { registerPayrollTools } from "./payroll";
import { registerFixedAssetTools } from "./fixed-assets";
import { registerInventoryTools } from "./inventory";
import { registerInventoryAssemblyTools } from "./inventory-assembly";
import { registerInventoryCatalogTools } from "./inventory-catalog";
import { registerPricingTools } from "./pricing";
import { registerPurchasingTools } from "./purchasing";
import { registerProcurementSettingsTools } from "./procurement-settings";
import { registerPurchaseOrderTools } from "./purchase-orders";
import { registerSalesReceiptTools } from "./sales-receipts";
import { registerQuoteTools } from "./quotes";
import { registerTaxProfileTools } from "./tax-profiles";
import { registerRecurringJournalTools } from "./recurring-journals";
import { registerProjectTools } from "./projects";
import { registerDebitNoteTools } from "./debit-notes";
import { registerLoanTools } from "./loans";
import { registerOpeningBalanceTools } from "./opening-balances";
import { registerAccrualScheduleTools } from "./accrual-schedules";
import { registerRevenueScheduleTools } from "./revenue-schedules";
import { registerExpenseCrudTools } from "./expense-crud";
import { registerExpenseTools } from "./expenses";
import { registerCreditNoteTools } from "./credit-notes";
import { registerCustomerCreditTools } from "./customer-credits";
import { registerRecurringTemplateTools } from "./recurring-templates";
import { registerPaymentTools } from "./payments";
import { registerPurchaseRequisitionTools } from "./purchase-requisitions";
import { registerLandedCostTools } from "./landed-costs";
import { registerBulkTools } from "./bulk";
import { registerInvoiceBulkTools } from "./invoice-bulk";
import { registerBillBulkTools } from "./bill-bulk";
import { registerBudgetTools } from "./budgets";
import { registerCostCenterTools } from "./cost-centers";
import { registerTagTools } from "./tags";
import { registerTaxPeriodTools } from "./tax-periods";
import { registerReminderTools } from "./reminders";
import { registerCrmTools } from "./crm";
import { registerWarehouseTools } from "./warehouses";
import { registerInventoryMovementTools } from "./inventory-movements";
import { registerPublicPortalTools } from "./public-portal";

export function registerAllTools(server: McpServer, ctx: AuthContext) {
  registerOrganizationTools(server, ctx);
  registerAccountTools(server, ctx);
  registerEntryTools(server, ctx);
  registerContactTools(server, ctx);
  registerInvoiceTools(server, ctx);
  registerInvoiceLifecycleTools(server, ctx);
  registerBillTools(server, ctx);
  registerReportTools(server, ctx);
  registerNotificationTools(server, ctx);
  registerRoleTools(server, ctx);
  registerTimeTrackingTools(server, ctx);
  registerWebhookTools(server, ctx);
  registerReportScheduleTools(server, ctx);
  registerApprovalTools(server, ctx);
  registerBankAccountTools(server, ctx);
  registerBankImportTools(server, ctx);
  registerBankTransactionReadTools(server, ctx);
  registerBankRuleTools(server, ctx);
  registerBankReconciliationTools(server, ctx);
  registerBankTransferTools(server, ctx);
  registerBankCategorizationTools(server, ctx);
  registerBankDocumentMatchTools(server, ctx);
  registerDocumentTools(server, ctx);
  registerIntegrationTools(server, ctx);
  registerEmailTools(server, ctx);
  registerPeriodCloseTools(server, ctx);
  registerImportExportTools(server, ctx);
  registerTrashTools(server, ctx);
  registerBackupTools(server, ctx);
  registerCurrencyTools(server, ctx);
  registerTaxRateTools(server, ctx);
  registerTaxLookupTools(server, ctx);
  registerTaxTools(server, ctx);
  registerConsolidationTools(server, ctx);
  registerPayrollTools(server, ctx);
  registerPayrollRunTools(server, ctx);
  registerPayrollPaymentTools(server, ctx);
  registerPayrollCompensationTools(server, ctx);
  registerPayrollMasterTools(server, ctx);
  registerPayrollConfigTools(server, ctx);
  registerPayrollTimeTools(server, ctx);
  registerFixedAssetTools(server, ctx);
  registerInventoryTools(server, ctx);
  registerInventoryAssemblyTools(server, ctx);
  registerInventoryMasterTools(server, ctx);
  registerInventoryCatalogTools(server, ctx);
  registerPricingTools(server, ctx);
  registerPurchasingTools(server, ctx);
  registerProcurementSettingsTools(server, ctx);
  registerGoodsReceiptTools(server, ctx);
  registerPurchaseOrderTools(server, ctx);
  registerSalesReceiptTools(server, ctx);
  registerQuoteTools(server, ctx);
  registerTaxProfileTools(server, ctx);
  registerRecurringJournalTools(server, ctx);
  registerProjectTools(server, ctx);
  registerDebitNoteTools(server, ctx);
  registerLoanTools(server, ctx);
  registerOpeningBalanceTools(server, ctx);
  registerAccrualScheduleTools(server, ctx);
  registerRevenueScheduleTools(server, ctx);
  registerExpenseCrudTools(server, ctx);
  registerExpenseTools(server, ctx);
  registerCreditNoteTools(server, ctx);
  registerCustomerCreditTools(server, ctx);
  registerRecurringTemplateTools(server, ctx);
  registerPaymentTools(server, ctx);
  registerPaymentBatchTools(server, ctx);
  registerScheduledPaymentTools(server, ctx);
  registerPurchaseRequisitionTools(server, ctx);
  registerLandedCostTools(server, ctx);
  registerInventoryValuationTools(server, ctx);
  registerBulkTools(server, ctx);
  registerInvoiceBulkTools(server, ctx);
  registerBillBulkTools(server, ctx);
  registerBudgetTools(server, ctx);
  registerCostCenterTools(server, ctx);
  registerTagTools(server, ctx);
  registerTaxPeriodTools(server, ctx);
  registerReminderTools(server, ctx);
  registerCrmTools(server, ctx);
  registerWarehouseTools(server, ctx);
  registerInventoryMovementTools(server, ctx);
  registerPublicPortalTools(server, ctx);
}
