import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { AuthContext } from "@/lib/api/auth-context";
import { requireRole } from "@/lib/api/require-role";
import { wrapTool } from "@/lib/mcp/errors";
import { catalogId } from "@/lib/api/inventory-catalog-wire";
import { mcpAdjustmentSchema, bulkAdjustmentSchema, transferCreateSchema, transferUpdateSchema, stockTakeCreateSchema, stockTakeUpdateSchema, stockTakeCountSchema, serialCreateSchema, lotCreateSchema, movementListSchema, allocationListSchema, chartSchema, postingDate, physicalQuantity } from "@/lib/api/inventory-movement-wire";
import { adjustInventory, bulkAdjustInventory, createInventoryTransfer, getTransfer, listTransfers, updateInventoryTransfer, completeInventoryTransfer, transferInventoryStock, listStockTakes, getStockTake, createStockTake, updateStockTake, deleteStockTake, countStockTakeLine, applyStockTake, listMovements, movementChart, warehouseStocks, createSerials, createLot, listAllocations } from "@/lib/api/inventory-movements";

export function registerInventoryMovementTools(server: McpServer, ctx: AuthContext) {
  const itemId = z.object({ inventoryItemId: catalogId.describe("Live owned item UUID") }).strict();
  const transferId = z.object({ transferId: catalogId.describe("Owned transfer UUID") }).strict();
  const takeId = z.object({ stockTakeId: catalogId.describe("Owned stock-take UUID") }).strict();
  server.registerTool("adjust_inventory_stock", { description: "Adjust whole-unit stock or book value atomically with GL and audit. amount/amountMinor are integer cents: positive write-down magnitude, signed revaluation delta. quantityDelta is whole units. Returns item/movement with Minor aliases and journalEntryId. Average-only value adjustment; period locks enforced.", inputSchema: mcpAdjustmentSchema }, p => wrapTool(ctx, () => adjustInventory(ctx, p.inventoryItemId, p, true)));
  server.registerTool("bulk_adjust_inventory_stock", { description: "Adjust 1..100 distinct items by signed whole-unit deltas, atomic stock/GL/audit. Returns { adjusted }.", inputSchema: bulkAdjustmentSchema }, p => wrapTool(ctx, () => bulkAdjustInventory(ctx, p)));
  server.registerTool("transfer_inventory_stock", { description: "Immediately transfer one owned item between live owned warehouses, positive int32 whole units. Atomic creation/completion/audit; global quantity/value unchanged, no GL. Returns { transfer }.", inputSchema: itemId.extend({ fromWarehouseId: catalogId.describe("Owned active source warehouse UUID"), toWarehouseId: catalogId.describe("Owned active destination warehouse UUID"), quantity: physicalQuantity.pipe(z.number().positive()).describe("Positive whole units"), notes: z.string().max(10000).optional().describe("Transfer note") }) }, p => wrapTool(ctx, async () => ({ transfer: await transferInventoryStock(ctx, { fromWarehouseId: p.fromWarehouseId, toWarehouseId: p.toWarehouseId, notes: p.notes, lines: [{ inventoryItemId: p.inventoryItemId, quantity: p.quantity }] }) })));
  server.registerTool("list_inventory_transfers", { description: "List owned transfers and scoped location metadata/whole-unit lines. Returns { data }.", inputSchema: z.object({}).strict() }, () => wrapTool(ctx, async () => ({ data: await listTransfers(ctx) })));
  server.registerTool("get_inventory_transfer", { description: "Read owned transfer and scoped locations/whole-unit lines. Returns { transfer }.", inputSchema: transferId }, p => wrapTool(ctx, async () => ({ transfer: await getTransfer(ctx, p.transferId) })));
  server.registerTool("create_inventory_transfer", { description: "Create draft transfer for 1..100 distinct items in whole units. Returns { transfer }; references validated and audit atomic.", inputSchema: transferCreateSchema }, p => wrapTool(ctx, async () => ({ transfer: await createInventoryTransfer(ctx, p) })));
  server.registerTool("update_inventory_transfer", { description: "Change open transfer status/notes. Completed/cancelled transfers cannot reopen. Returns { transfer }.", inputSchema: transferUpdateSchema.extend(transferId.shape) }, p => wrapTool(ctx, async () => { const { transferId, ...fields } = p; return { transfer: await updateInventoryTransfer(ctx, transferId, fields) }; }));
  server.registerTool("complete_inventory_transfer", { description: "Complete open transfer atomically; sufficient source whole units required. Repeated completion rejects without moving stock. Returns { transfer }; no GL.", inputSchema: transferId }, p => wrapTool(ctx, async () => ({ transfer: await completeInventoryTransfer(ctx, p.transferId) })));
  server.registerTool("list_stock_takes", { description: "List owned stock takes with item counts. Returns { stockTakes }.", inputSchema: z.object({}).strict() }, () => wrapTool(ctx, async () => ({ stockTakes: await listStockTakes(ctx) })));
  server.registerTool("get_stock_take", { description: "Get owned stock take and lines; whole-unit counts and signed valueAdjustment cents plus valueAdjustmentMinor. Returns { stockTake }.", inputSchema: takeId }, p => wrapTool(ctx, async () => ({ stockTake: await getStockTake(ctx, p.stockTakeId) })));
  server.registerTool("create_stock_take", { description: "Create draft count, snapshot active owned items' global or warehouse whole units. Returns { stockTake }; audit atomic.", inputSchema: stockTakeCreateSchema }, p => wrapTool(ctx, async () => ({ stockTake: await createStockTake(ctx, p) })));
  server.registerTool("update_stock_take", { description: "Change open count name/notes/status. Complete via apply_stock_take only. Returns { stockTake }.", inputSchema: stockTakeUpdateSchema.extend(takeId.shape) }, p => wrapTool(ctx, async () => { const { stockTakeId, ...fields } = p; return { stockTake: await updateStockTake(ctx, stockTakeId, fields) }; }));
  server.registerTool("delete_stock_take", { description: "Delete owned draft stock take and lines atomically with audit. Returns { success: true }.", inputSchema: takeId }, p => wrapTool(ctx, () => deleteStockTake(ctx, p.stockTakeId)));
  server.registerTool("count_stock_take_line", { description: "Count a line of an owned in-progress take, nonnegative int32 whole units. Returns { line } with signed valueAdjustmentMinor when available.", inputSchema: stockTakeCountSchema.extend({ ...takeId.shape, lineId: catalogId.describe("Line UUID belonging to this take") }) }, p => wrapTool(ctx, async () => ({ line: await countStockTakeLine(ctx, p.stockTakeId, p.lineId, { countedQuantity: p.countedQuantity }) })));
  server.registerTool("apply_stock_take", { description: "Apply every counted line against LIVE global or warehouse whole units. Atomically adjusts cost flow, GL, lines, completion and audit with period locks. Returns stockTake, adjustedCount and journalEntryIds; retries reject without reposting.", inputSchema: takeId.extend({ date: postingDate.optional().describe("Gregorian posting date, defaults to UTC today") }) }, p => wrapTool(ctx, () => applyStockTake(ctx, p.stockTakeId, p.date)));
  server.registerTool("list_inventory_movements", { description: "List scoped movements in whole units; unitCost/value are integer cents with canonical Minor aliases. Returns { movements, total, page, limit }; filters are owned IDs.", inputSchema: movementListSchema }, p => wrapTool(ctx, async () => { requireRole(ctx, "manage:inventory"); const r = await listMovements(ctx, p); return { movements: r.data, total: r.pagination.total, page: r.pagination.page, limit: r.pagination.limit }; }));
  server.registerTool("get_inventory_movement_chart", { description: "Read physical-unit movement chart (30d daily, 90d weekly, 12m monthly). Returns { data, period, groupBy }; sums checked for safe numeric range, no money scaling.", inputSchema: chartSchema }, p => wrapTool(ctx, () => movementChart(ctx, p)));
  server.registerTool("get_inventory_warehouse_stock", { description: "List live owned locations for an owned item's whole-unit stock. Returns { data }; no monetary fields.", inputSchema: itemId }, p => wrapTool(ctx, async () => ({ data: await warehouseStocks(ctx, p.inventoryItemId, true) })));
  server.registerTool("create_inventory_serials", { description: "Add distinct serial allocation metadata to owned item/location. No receipt, quantity or GL change. Returns { data }; audit atomic.", inputSchema: serialCreateSchema.extend(itemId.shape) }, p => wrapTool(ctx, async () => { const { inventoryItemId, ...fields } = p; return { data: await createSerials(ctx, inventoryItemId, fields) }; }));
  server.registerTool("list_inventory_serials", { description: "List serial allocation metadata with owned location, pagination/status. Returns { data, pagination }; no money fields.", inputSchema: allocationListSchema.extend(itemId.shape) }, p => wrapTool(ctx, () => { const { inventoryItemId, ...fields } = p; return listAllocations(ctx, inventoryItemId, fields); }));
  server.registerTool("create_inventory_lot", { description: "Add lot/batch allocation metadata, positive int32 whole units and Gregorian dates. No receipt or GL change. Returns { lot }; audit atomic.", inputSchema: lotCreateSchema.extend(itemId.shape) }, p => wrapTool(ctx, async () => { const { inventoryItemId, ...fields } = p; return { lot: await createLot(ctx, inventoryItemId, fields) }; }));
  server.registerTool("list_inventory_lots", { description: "List owned lot/batch metadata with whole-unit quantity/availableQuantity and owned location. Returns { data, pagination }; no money fields.", inputSchema: allocationListSchema.omit({ status: true }).extend(itemId.shape) }, p => wrapTool(ctx, () => { const { inventoryItemId, ...fields } = p; return listAllocations(ctx, inventoryItemId, fields, true); }));
}
