import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { AuthContext } from "@/lib/api/auth-context";
import { wrapTool } from "@/lib/mcp/errors";
import { landedCreateSchema, landedUpdateSchema, landedListSchema, landedIdSchema } from "@/lib/api/landed-cost-wire";
import { createLandedCost, listLandedCosts, getLandedCost, updateLandedCost, deleteLandedCost, allocateLandedCost } from "@/lib/api/landed-costs";
export function registerLandedCostTools(server: McpServer, ctx: AuthContext) {
  server.registerTool("list_landed_costs", { description: "List owned landed cost batches, paginated; returns allocations, total, page, limit. Numeric stored minor amounts (USD cents) plus Minor strings; PO quantities are hundredths.", inputSchema: landedListSchema }, p => wrapTool(ctx, () => listLandedCosts(ctx, p)));
  server.registerTool("get_landed_cost", { description: "Read an owned batch with components, source bill/PO and line allocations. Numeric stored minor amounts plus Minor strings; allocationBasisExact is minor value for by_value or quantity hundredths for by_quantity.", inputSchema: landedIdSchema }, p => wrapTool(ctx, async () => ({ allocation: await getLandedCost(ctx, p.landedCostId) })));
  server.registerTool("create_landed_cost", { description: "Create owned draft atomically with audit; manage:purchases required. Legacy component amount is two-decimal major units (12.50 -> 1250 for every currency); amountMinor is canonical stored integer units (USD cents), safe Number range. Both must agree after rounding. Returns allocation with totalCostAmountMinor. Weight/manual methods unsupported.", inputSchema: landedCreateSchema }, p => wrapTool(ctx, async () => ({ allocation: await createLandedCost(ctx, p) })));
  server.registerTool("update_landed_cost", { description: "Update owned draft name/allocation method atomically with audit; manage:purchases required. Allocated history immutable. Returns allocation with totalCostAmountMinor.", inputSchema: landedIdSchema.extend(landedUpdateSchema.shape) }, p => wrapTool(ctx, async () => { const { landedCostId, ...input } = p; return { allocation: await updateLandedCost(ctx, landedCostId, input) }; }));
  server.registerTool("delete_landed_cost", { description: "Soft-delete owned draft atomically with audit; manage:purchases required. Allocated history immutable. Returns success.", inputSchema: landedIdSchema }, p => wrapTool(ctx, () => deleteLandedCost(ctx, p.landedCostId)));
  server.registerTool("allocate_landed_cost", { description: "Capitalize owned draft atomically with balanced inventory/clearing journal and audit on unlocked UTC today; manage:purchases required. Batch/PO must use base currency and every PO line must reference positive on-hand average/FIFO stock. Exact largest-remainder allocation conserves each component; FIFO residual cents persist separately from historical unit cost. Repeated/concurrent calls cannot duplicate posting. Returns allocation, lineAllocations with Minor aliases, journalEntryId (null for zero cost).", inputSchema: landedIdSchema }, p => wrapTool(ctx, () => allocateLandedCost(ctx, p.landedCostId)));
}
