import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { AuthContext } from "@/lib/api/auth-context";
import { wrapTool } from "@/lib/mcp/errors";
import { outputId, emptyOutputSchema, reportSchema, selfProfileSchema, taxGenerateSchema, taxListSchema } from "@/lib/api/payroll-output-wire";
import { generatePayslips, listRunPayslips, getPayslip, listEmployeePayslips, payrollSummary, payrollLaborCost, payrollTaxLiability, payrollYoy,
  exportPayroll, getSelfProfile, updateSelfProfile, listSelfPayslips, generateTaxForms, listTaxForms, getTaxForm, taxFormPdfData } from "@/lib/api/payroll-outputs";

export function registerPayrollOutputTools(server: McpServer, ctx: AuthContext) {
  server.registerTool("generate_payslips", { description: "Generate missing snapshots for a completed run; returns count of newly generated payslips. Retries do not duplicate snapshots; YTD includes only this Gregorian year. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema.extend({ payRunId: outputId.describe("Completed owned payroll run UUID") }) }, args => wrapTool(ctx, async () => generatePayslips(ctx, args.payRunId)));
  server.registerTool("list_payslips", { description: "List a run's payslips; returns payslips with employeeName, amounts, exact aliases and currency. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema.extend({ payRunId: outputId.describe("Owned payroll run UUID") }) }, args => wrapTool(ctx, async () => ({ payslips: await listRunPayslips(ctx, args.payRunId) })));
  server.registerTool("get_payslip", { description: "Get an owned payslip and atomically mark it viewed; returns payslip, employee, run and item. Requires view:payslips. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema.extend({ id: outputId.describe("Owned payslip UUID") }) }, args => wrapTool(ctx, async () => ({ payslip: await getPayslip(ctx, args.id) })));
  server.registerTool("list_employee_payslips", { description: "List an owned employee's payslips; returns data. Requires view:payslips. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema.extend({ employeeId: outputId.describe("Owned employee UUID") }) }, args => wrapTool(ctx, async () => ({ data: await listEmployeePayslips(ctx, args.employeeId) })));
  server.registerTool("get_payroll_summary", { description: "Get completed-run summary in one saved base currency; returns summary. Mixed currencies reject. Requires view:payroll-reports. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: reportSchema }, args => wrapTool(ctx, async () => payrollSummary(ctx, args)));
  server.registerTool("get_payroll_labor_cost", { description: "Get completed-run cost by department and employee currency; returns data. Requires view:payroll-reports. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: reportSchema }, args => wrapTool(ctx, async () => payrollLaborCost(ctx, args)));
  server.registerTool("get_payroll_tax_liability", { description: "Get withholding totals by employee with totalTax in one currency; returns data/totalTax. Mixed currencies reject. Requires view:payroll-reports. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: reportSchema }, args => wrapTool(ctx, async () => payrollTaxLiability(ctx, args)));
  server.registerTool("get_payroll_yoy", { description: "Get completed-run totals by Gregorian month in one saved base currency; returns data. Requires view:payroll-reports. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema }, () => wrapTool(ctx, async () => payrollYoy(ctx)));
  server.registerTool("export_payroll_csv", { description: "Export completed payroll; returns csv, filename and contentType. Existing monetary columns are exact two-decimal cents values; additive Currency column identifies item currency. Requires view:payroll-reports. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: reportSchema }, args => wrapTool(ctx, async () => exportPayroll(ctx, args)));
  server.registerTool("get_payroll_self_profile", { description: "Get only the authenticated member's live employee profile; returns employee with salary/hourlyRate aliases. Requires self-service:payroll. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema }, () => wrapTool(ctx, async () => ({ employee: await getSelfProfile(ctx) })));
  server.registerTool("update_payroll_self_profile", { description: "Update only your employee email/bank account number; returns employee. No salary/currency edits. Requires self-service:payroll. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: selfProfileSchema }, args => wrapTool(ctx, async () => ({ employee: await updateSelfProfile(ctx, args) })));
  server.registerTool("list_payroll_self_payslips", { description: "List only your employee's payslips; returns data. Requires self-service:payroll. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema }, () => wrapTool(ctx, async () => ({ data: await listSelfPayslips(ctx) })));
  server.registerTool("generate_tax_forms", { description: "Generate a new year-end W-2/1099-NEC batch from saved USD amounts; returns generation/formsGenerated. Requires manage:payroll. 1099-MISC is unsupported; W-2 needs saved tax/deduction breakdowns; no statutory-rate estimates. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: taxGenerateSchema }, args => wrapTool(ctx, async () => generateTaxForms(ctx, args)));
  server.registerTool("list_tax_forms", { description: "List organization tax-form batches and nested forms; returns data/pagination. Requires manage:payroll. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: taxListSchema }, args => wrapTool(ctx, async () => listTaxForms(ctx, args)));
  server.registerTool("get_tax_form", { description: "Get an owned tax form and generation; returns the form. Requires manage:payroll. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema.extend({ id: outputId.describe("Owned tax form UUID") }) }, args => wrapTool(ctx, async () => getTaxForm(ctx, args.id)));
  server.registerTool("get_tax_form_pdf_data", { description: "Get the existing PDF endpoint's JSON form data and note; returns no PDF file. Requires manage:payroll. Money remains safe integer cents with matching canonical Minor strings, absolute max 9007199254740991. Dates are Gregorian; amounts are never rescaled.", inputSchema: emptyOutputSchema.extend({ id: outputId.describe("Owned tax form UUID") }) }, args => wrapTool(ctx, async () => taxFormPdfData(ctx, args.id)));
}
