import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { db } from "@/lib/db";
import {
  purchaseOrder,
  procurementSettings,
  organization,
} from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";
import { notDeleted } from "@/lib/db/soft-delete";
import { requireRole } from "@/lib/api/require-role";
import { formatMoney } from "@/lib/money";
import { wrapTool } from "@/lib/mcp/errors";
import { sendDocumentEmail } from "@/lib/email/document-sender";
import {
  getProcurementSettings,
  threeWayMatch,
  DEFAULT_PROCUREMENT_SETTINGS,
} from "@/lib/api/procurement";
import { buildSupplierStatement, NotASupplierError } from "@/lib/api/supplier-statement";
import {
  buildBatchRemittance,
  resolveBatchPaymentDate,
  type RemittanceGroup,
} from "@/lib/api/remittance";
import type { AuthContext } from "@/lib/api/auth-context";

function renderRemittanceHtml(
  orgName: string,
  group: RemittanceGroup,
  batchName: string,
  paymentDate: string,
  personalMessage?: string
): string {
  const formatDate = (d: string) => {
    const dt = new Date(d + "T00:00:00");
    return dt.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  };
  const fmt = (cents: number) => formatMoney(cents, group.currencyCode);

  const rows = group.lines
    .map(
      (l) => `
      <tr>
        <td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:12px;">${formatDate(l.billDate)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:12px;">${l.billNumber}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:12px;">${l.billReference || "-"}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:12px;text-align:right;font-family:monospace;">${fmt(l.billTotal)}</td>
        <td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:12px;text-align:right;font-family:monospace;">${fmt(l.amountPaid)}</td>
      </tr>`
    )
    .join("\n");

  return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8" /></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#111;padding:0;margin:0;">
  <div style="max-width:700px;margin:0 auto;padding:32px 20px;">
    <h1 style="font-size:20px;font-weight:700;margin:0 0 4px;">Remittance Advice</h1>
    <p style="font-size:13px;color:#666;margin:0 0 24px;">${orgName}</p>
    <table style="width:100%;margin-bottom:16px;" cellpadding="0" cellspacing="0">
      <tr>
        <td style="font-size:13px;"><strong>${group.contactName}</strong></td>
        <td style="font-size:12px;text-align:right;color:#666;">Payment date: ${formatDate(paymentDate)}</td>
      </tr>
    </table>
    ${
      personalMessage
        ? `<p style="font-size:13px;color:#525f7f;line-height:22px;margin:0 0 24px;white-space:pre-wrap;">${personalMessage}</p>`
        : ""
    }
    <p style="font-size:13px;color:#444;margin:0 0 16px;">
      The following bills have been paid${batchName ? ` (batch: ${batchName})` : ""}:
    </p>
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px;" cellpadding="0" cellspacing="0">
      <thead>
        <tr style="background:#f5f5f5;">
          <th style="padding:8px;text-align:left;font-size:10px;text-transform:uppercase;color:#888;font-weight:500;border-bottom:1px solid #ddd;">Bill Date</th>
          <th style="padding:8px;text-align:left;font-size:10px;text-transform:uppercase;color:#888;font-weight:500;border-bottom:1px solid #ddd;">Bill #</th>
          <th style="padding:8px;text-align:left;font-size:10px;text-transform:uppercase;color:#888;font-weight:500;border-bottom:1px solid #ddd;">Reference</th>
          <th style="padding:8px;text-align:right;font-size:10px;text-transform:uppercase;color:#888;font-weight:500;border-bottom:1px solid #ddd;">Bill Total</th>
          <th style="padding:8px;text-align:right;font-size:10px;text-transform:uppercase;color:#888;font-weight:500;border-bottom:1px solid #ddd;">Amount Paid</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
        <tr style="background:#f9f9f9;">
          <td colspan="4" style="padding:8px;font-size:12px;font-weight:600;border-bottom:1px solid #ddd;">Total Paid</td>
          <td style="padding:8px;font-size:12px;font-weight:600;text-align:right;font-family:monospace;border-bottom:1px solid #ddd;">${fmt(group.totalPaid)}</td>
        </tr>
      </tbody>
    </table>
    <p style="font-size:11px;color:#999;margin-top:24px;">
      This remittance advice was generated by ${orgName}.
    </p>
  </div>
</body>
</html>`;
}

/**
 * Accounts-payable / purchasing MCP tools:
 * goods receipts (GRN), three-way match,
 * procurement settings, supplier statements, and remittance advice (data + email).
 * Purchase order and receipt contracts live in dedicated tool files. This file retains
 * settings, matching, supplier statement and remittance operations.
 *
 * CONVENTIONS (matching the rest of the codebase):
 *  • MONETARY AMOUNTS are integer cents (e.g. $12.50 = 1250). Unit prices on
 *    create_purchase_order are DECIMAL numbers (e.g. 12.50) for convenience and
 *    are converted to cents internally.
 *  • QUANTITIES on inputs are WHOLE units (decimals allowed, e.g. 2.5) and are
 *    stored internally x100 (so 5 units = 500).
 *  • All tools are org-scoped via the AuthContext and use direct Drizzle access
 *    (no HTTP self-calls). Stock-moving tools post the matching double-entry
 *    journal so the GL and perpetual inventory stay in lock-step.
 */
export function registerPurchasingTools(server: McpServer, ctx: AuthContext) {
  server.tool(
    "get_purchasing_supplier_statement",
    "Get an accounts-payable statement for a supplier contact over a date range: bills (increase what we owe), debit notes (reduce it), and payments made (reduce it), with a running balance of what we owe the supplier (positive = we owe them). Date params are YYYY-MM-DD and default to the last 12 months. All amounts are integer cents. Errors if the contact is not a supplier.",
    {
      contactId: z.string().describe("Supplier contact UUID"),
      startDate: z
        .string()
        .optional()
        .describe("Start of the period (YYYY-MM-DD); defaults to 12 months ago"),
      endDate: z
        .string()
        .optional()
        .describe("End of the period (YYYY-MM-DD); defaults to today"),
    },
    (params) =>
      wrapTool(ctx, async () => {
        try {
          const statement = await buildSupplierStatement(
            ctx.organizationId,
            params.contactId,
            params.startDate,
            params.endDate
          );
          if (!statement) throw new Error("Contact not found");
          return { statement };
        } catch (err) {
          if (err instanceof NotASupplierError) {
            throw new Error(err.message);
          }
          throw err;
        }
      })
  );

  // ─── Generate remittance advice for a payment batch ─────────────────
  server.tool(
    "generate_remittance",
    "Generate remittance advice for a payment batch: groups the batch's paid items by supplier and lists, per supplier, which bills were paid and the amount applied to each. All amounts are integer cents. This returns the structured remittance data (it does not email it). Optionally filter to a single supplier with contactId.",
    {
      paymentBatchId: z.string().describe("Payment batch UUID"),
      contactId: z
        .string()
        .optional()
        .describe("Optional: return only the remittance for this supplier contact UUID"),
    },
    (params) =>
      wrapTool(ctx, async () => {
        requireRole(ctx, "manage:payments");

        const result = await buildBatchRemittance(
          ctx.organizationId,
          params.paymentBatchId
        );
        if (!result) throw new Error("Payment batch not found");

        let groups = result.groups;
        if (params.contactId) {
          groups = groups.filter((g) => g.contactId === params.contactId);
          if (groups.length === 0) {
            throw new Error(
              "No remittance found for the given contact in this batch"
            );
          }
        }

        const paymentDate = resolveBatchPaymentDate(result.batch);

        return {
          batch: {
            id: result.batch.id,
            name: result.batch.name,
            status: result.batch.status,
            totalAmount: result.batch.totalAmount,
            paymentCount: result.batch.paymentCount,
            paymentDate,
          },
          remittances: groups,
        };
      })
  );

  // ─── Email remittance advice for a payment batch ────────────────────
  server.tool(
    "send_payment_batch_remittance",
    "Email remittance advices for a payment batch to suppliers. By default emails every supplier in the batch that has an email address; pass contactId to send to only one supplier. Returns which suppliers were sent and which were skipped (e.g. no email on file). Suppliers without an email are skipped, not errored.",
    {
      batchId: z.string().describe("The UUID of the payment batch"),
      contactId: z
        .string()
        .optional()
        .describe(
          "If set, only email the remittance for this one supplier; otherwise all suppliers in the batch are emailed"
        ),
      personalMessage: z
        .string()
        .optional()
        .describe("Optional message included at the top of the remittance email"),
    },
    (params) =>
      wrapTool(ctx, async () => {
        requireRole(ctx, "manage:payments");

        const result = await buildBatchRemittance(
          ctx.organizationId,
          params.batchId
        );
        if (!result) throw new Error("Payment batch not found");

        const org = await db.query.organization.findFirst({
          where: eq(organization.id, ctx.organizationId),
        });
        const orgName = org?.name || "Organization";
        const paymentDate = resolveBatchPaymentDate(result.batch);

        let groups = result.groups;
        if (params.contactId) {
          groups = groups.filter((g) => g.contactId === params.contactId);
          if (!groups.length) {
            throw new Error(
              "No remittance found for the given contact in this batch"
            );
          }
        }

        const sent: Array<{ contactId: string; recipientEmail: string }> = [];
        const skipped: Array<{ contactId: string; reason: string }> = [];

        for (const group of groups) {
          if (!group.contactEmail) {
            skipped.push({
              contactId: group.contactId,
              reason: "Supplier has no email address",
            });
            continue;
          }

          const html = renderRemittanceHtml(
            orgName,
            group,
            result.batch.name,
            paymentDate,
            params.personalMessage
          );

          await sendDocumentEmail({
            orgId: ctx.organizationId,
            userId: ctx.userId,
            documentType: "remittance_advice",
            documentId: params.batchId,
            recipientEmail: group.contactEmail,
            subject: `Remittance advice from ${orgName} — ${formatMoney(group.totalPaid, group.currencyCode)}`,
            body: html,
            attachPdf: false,
            replyTo: org?.contactEmail || undefined,
          });

          sent.push({
            contactId: group.contactId,
            recipientEmail: group.contactEmail,
          });
        }

        return { success: true, sent, skipped };
      })
  );

  // ─── Three-way-match preview ────────────────────────────────────────
  server.tool(
    "three_way_match_purchase_order",
    "Run a three-way match on a purchase order: compare ordered (PO) vs received (GRN) vs billed quantities and prices against the org's procurement tolerances. Optionally pass a proposed bill (`billLines` with quantities in whole units and optional unitPrice in cents) to evaluate before billing. Returns per-line status (matched/warning/blocked), variances, and an overall status. No changes are made.",
    {
      purchaseOrderId: z.string().describe("Purchase order UUID to evaluate"),
      billLines: z
        .array(
          z.object({
            purchaseOrderLineId: z.string().describe("PO line UUID"),
            quantity: z.number().positive().describe("Proposed quantity to bill, in whole units"),
            unitPrice: z.number().int().min(0).optional().describe("Proposed bill unit price in cents (defaults to the PO price)"),
          })
        )
        .optional()
        .describe("Proposed bill lines to evaluate. Omit to evaluate the current ordered/received/billed state only."),
    },
    (params) =>
      wrapTool(ctx, async () => {
        const po = await db.query.purchaseOrder.findFirst({
          where: and(
            eq(purchaseOrder.id, params.purchaseOrderId),
            eq(purchaseOrder.organizationId, ctx.organizationId),
            notDeleted(purchaseOrder.deletedAt)
          ),
          with: { lines: true },
        });
        if (!po) throw new Error("Purchase order not found");

        const settings = await getProcurementSettings(ctx.organizationId);
        const proposedById = new Map(
          (params.billLines ?? []).map((b) => [b.purchaseOrderLineId, b])
        );

        const matchInput = po.lines.map((l) => {
          const proposed = proposedById.get(l.id);
          return {
            purchaseOrderLineId: l.id,
            description: l.description,
            quantityOrdered: l.quantity,
            quantityReceived: l.quantityReceived,
            quantityBilled: l.quantityBilled,
            quantityToBill: proposed ? Math.round(proposed.quantity * 100) : 0,
            unitPriceOrdered: l.unitPrice,
            unitPriceBilled: proposed?.unitPrice ?? l.unitPrice,
          };
        });

        return { match: threeWayMatch(matchInput, settings), settings };
      })
  );

  // ─── Get procurement settings ───────────────────────────────────────
  server.tool(
    "get_procurement_settings",
    "Get the org's procurement (three-way-match) settings. Tolerances are in basis points (500 = 5%). requireGrnBeforeBill blocks billing un-received goods; blockOverBill blocks billing beyond the ordered quantity. Returns safe defaults (no tolerance, nothing blocked) when never configured.",
    {},
    () =>
      wrapTool(ctx, async () => {
        const existing = await db.query.procurementSettings.findFirst({
          where: eq(procurementSettings.organizationId, ctx.organizationId),
        });
        return {
          procurementSettings:
            existing ?? { organizationId: ctx.organizationId, ...DEFAULT_PROCUREMENT_SETTINGS },
        };
      })
  );

  // ─── Update procurement settings ────────────────────────────────────
  server.tool(
    "update_procurement_settings",
    "Update the org's procurement (three-way-match) settings (upsert). Tolerances are in basis points (500 = 5%). Only provided fields are changed.",
    {
      priceTolerancePercent: z.number().int().min(0).max(100000).optional().describe("Price tolerance in basis points (500 = 5%)"),
      qtyTolerancePercent: z.number().int().min(0).max(100000).optional().describe("Quantity tolerance in basis points (500 = 5%)"),
      requireGrnBeforeBill: z.boolean().optional().describe("Block billing goods that have not been received via a GRN"),
      blockOverBill: z.boolean().optional().describe("Block billing beyond the ordered quantity"),
    },
    (params) =>
      wrapTool(ctx, async () => {
        requireRole(ctx, "manage:bills");

        const existing = await db.query.procurementSettings.findFirst({
          where: eq(procurementSettings.organizationId, ctx.organizationId),
        });

        let saved;
        if (existing) {
          [saved] = await db
            .update(procurementSettings)
            .set({
              ...(params.priceTolerancePercent !== undefined && { priceTolerancePercent: params.priceTolerancePercent }),
              ...(params.qtyTolerancePercent !== undefined && { qtyTolerancePercent: params.qtyTolerancePercent }),
              ...(params.requireGrnBeforeBill !== undefined && { requireGrnBeforeBill: params.requireGrnBeforeBill }),
              ...(params.blockOverBill !== undefined && { blockOverBill: params.blockOverBill }),
              updatedAt: new Date(),
            })
            .where(eq(procurementSettings.organizationId, ctx.organizationId))
            .returning();
        } else {
          [saved] = await db
            .insert(procurementSettings)
            .values({
              organizationId: ctx.organizationId,
              priceTolerancePercent: params.priceTolerancePercent ?? DEFAULT_PROCUREMENT_SETTINGS.priceTolerancePercent,
              qtyTolerancePercent: params.qtyTolerancePercent ?? DEFAULT_PROCUREMENT_SETTINGS.qtyTolerancePercent,
              requireGrnBeforeBill: params.requireGrnBeforeBill ?? DEFAULT_PROCUREMENT_SETTINGS.requireGrnBeforeBill,
              blockOverBill: params.blockOverBill ?? DEFAULT_PROCUREMENT_SETTINGS.blockOverBill,
            })
            .returning();
        }

        return { procurementSettings: saved };
      })
  );
}
